name: Deploy Nebula app
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: self-hosted
    environment: pi
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub (or your container registry)
        uses: docker/login-action@v1
        with:
          # You need to set your DockerHub username and access token in the repository secret
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          # Replace 'yourusername/yourrepository' with your DockerHub username and repository name
          push: true
          tags: raphaelvguy/nebula:latest
          platforms: linux/amd64, linux/arm64
  deploy:
    runs-on: self-hosted
    environment: pi
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: pi
          key: ${{ secrets.SSH_KEY }}
          script: |
            /home/pi/.local/bin/docker-compose -f /home/pi/docker-compose-nebula.yml pull
            /home/pi/.local/bin/docker-compose -f /home/pi/docker-compose-nebula.yml up -d
